using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Security;
using Content.Shared.StationRecords;
using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Client._CD.Records.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterRecordViewer : FancyWindow
{
    public static readonly Color BackgroundColor = Color.FromHex("#25252a"); // Dark grey
    public static readonly Color ContentPanelColor = Color.FromHex("#1a1a1a"); // Darker grey for content areas
    public static readonly Color BorderColor = Color.FromHex("#404040"); // Light grey border
    public static readonly Color ErrorColor = Color.FromHex("#ff0000"); // Red for validation errors

    public event Action<uint?>? OnListingItemSelected;
    public event Action<StationRecordFilterType, string?>? OnFiltersChanged;

    private bool _isPopulating;
    private StationRecordFilterType _filterType;
    private CharacterRecordConsoleState? _lastState;

    private RecordConsoleType? _type;

    private readonly RecordEntryViewPopup _entryView = new();
    private List<PlayerProvidedCharacterRecords.RecordEntry>? _entries;

    private DialogWindow? _wantedReasonDialog;

    /// <summary>
    /// The key to the record of the currently selected item in the listing.
    /// </summary>
    private uint? _selectedListingKey;

    public event Action<SecurityStatus, string?>? OnSetSecurityStatus;

    public uint? SecurityWantedStatusMaxLength;

    public CharacterRecordViewer()
    {
        RobustXamlLoader.Load(this);

        // Use the same filters as the station records consoles.
        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            RecordFilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        // Show the security statuses used by the criminal records console.
        foreach (var status in Enum.GetValues<SecurityStatus>())
        {
            var name = Loc.GetString($"criminal-records-status-{status.ToString().ToLower()}");
            StatusOptionButton.AddItem(name, (int)status);
        }

        CharacterListing.OnItemSelected += _ =>
        {
            if (!CharacterListing.GetSelected().Any())
                return;
            var selected = CharacterListing.GetSelected().First();
            var key = (uint)selected.Metadata!;
            _selectedListingKey = key;
            if (!_isPopulating)
                OnListingItemSelected?.Invoke(key);
        };

        CharacterListing.OnItemDeselected += _ =>
        {
            // When we populate the records, we clear the contents of the listing.
            // This could cause a deselection but we don't want to really deselect because it would
            // interrupt what the player is doing.
            if (!_isPopulating)
                OnListingItemSelected?.Invoke(null);
            _selectedListingKey = null;
        };

        RecordFilters.OnPressed += _ =>
        {
            OnFiltersChanged?.Invoke(_filterType, RecordFiltersValue.Text);
        };

        RecordFiltersReset.OnPressed += _ =>
        {
            OnFiltersChanged?.Invoke(StationRecordFilterType.Name, null);
            RecordFiltersValue.Clear();
        };

        RecordFiltersValue.OnTextEntered += text =>
        {
            OnFiltersChanged?.Invoke(_filterType, text.Text);
        };

        RecordFilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;
            _filterType = type;
            RecordFilterType.SelectId(eventArgs.Id);
        };

        RecordEntryViewButton.OnPressed += _ =>
        {
            if (_entries == null || !RecordEntryList.GetSelected().Any())
                return;
            var idx = RecordEntryList.IndexOf(RecordEntryList.GetSelected().First());
            _entryView.SetContents(_entries[idx]);
            _entryView.Open();
        };

        StatusOptionButton.OnItemSelected += args =>
        {
            var status = (SecurityStatus)args.Id;
            // This should reflect SetStatus in CriminalRecordsConsoleWindow.xaml.cs
            if (status is SecurityStatus.Wanted or SecurityStatus.Suspected or SecurityStatus.Hostile)
                SetStatusWithReason(status);
            else
                OnSetSecurityStatus?.Invoke(status, null);
        };

        OnClose += () =>
        {
            _entryView.Close();
            _wantedReasonDialog?.Close();
        };

        // Admin console entry type selector
        RecordEntryViewType.AddItem(Loc.GetString("humanoid-profile-editor-cd-records-employment"));
        RecordEntryViewType.AddItem(Loc.GetString("department-Medical"));
        RecordEntryViewType.AddItem(Loc.GetString("department-Security"));
        RecordEntryViewType.OnItemSelected += args =>
        {
            if (args.Id == RecordEntryViewType.SelectedId)
                return;
            RecordEntryViewType.SelectId(args.Id);
            if (_lastState is { } state)
                UpdateState(state);
        };
        SetSecurityStatusEnabled(false);
    }

    // If we are using wizden's class we might as well use their localization.
    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }

    /// <summary>
    /// Select the record in the listing for the given key.
    /// </summary>
    /// <param name="key">The index of the record in the dictionary</param>
    private void SelectRecordKey(uint? key)
    {
        if (_selectedListingKey == key)
            return;
        _selectedListingKey = key;

        _isPopulating = true;

        CharacterListing.ClearSelected();

        // I wish there was a better way of doing this
        if (key != null)
        {
            foreach (var item in CharacterListing)
            {
                if ((uint)item.Metadata! == key)
                {
                    item.Selected = true;
                    break;
                }
            }
        }

        _isPopulating = false;
    }

    private bool CharacterListNeedsRepopulating(IReadOnlyDictionary<uint, string> newKeys)
    {
        var newCount = newKeys.Count;
        if (newCount != CharacterListing.Count)
            return true;

        foreach (var item in CharacterListing)
        {
            var key = (uint)item.Metadata!;
            if (!newKeys.TryGetValue(key, out var info) ||
                item.Text != info)
                return true;
        }

        return false;
    }

    public void UpdateState(CharacterRecordConsoleState state)
    {
        _lastState = state;
        #region Visibility

        RecordEntryViewType.Visible = false;
        _type = state.ConsoleType;

        // Disable listing if we don't have one selected
        if (state.CharacterList == null)
        {
            CharacterListingStatus.Visible = true;
            CharacterListing.Visible = false;
            CharacterListingStatus.Text = Loc.GetString("cd-record-viewer-empty-state");
            RecordContainer.Visible = false;
            RecordContainerStatus.Visible = false;
            return;
        }

        CharacterListingStatus.Visible = false;
        CharacterListing.Visible = true;

        // Enable extended filtering only for admin and security consoles
        switch (_type)
        {
            case RecordConsoleType.Employment:
                RecordFilterType.Visible = false;
                RecordFilterType.SelectId((int)StationRecordFilterType.Name);

                Title = Loc.GetString("cd-character-records-viewer-title-employ");
                break;
            case RecordConsoleType.Medical:
                RecordFilterType.Visible = false;
                RecordFilterType.SelectId((int)StationRecordFilterType.Name);

                Title = Loc.GetString("cd-character-records-viewer-title-med");
                break;
            case RecordConsoleType.Security:
                RecordFilterType.Visible = true;

                Title = Loc.GetString("cd-character-records-viewer-title-sec");
                break;
            case RecordConsoleType.Admin:
                RecordFilterType.Visible = true;
                Title = Loc.GetString("cd-character-records-viewer-title-admin");
                RecordEntryViewType.Visible = true;

                break;
        }

        #endregion

        #region PopulateListing

        if (state.Filter != null)
        {
            RecordFiltersValue.SetText(state.Filter.Value);
            RecordFilterType.SelectId((int) state.Filter.Type);
        }

        if (CharacterListNeedsRepopulating(state.CharacterList))
        {
            _isPopulating = true;

            CharacterListing.Clear();

            foreach (var (key, name) in state.CharacterList.OrderBy(record => record.Value))
                CharacterListing.AddItem(name, metadata: key);

            _isPopulating = false;
        }

        SelectRecordKey(state.SelectedIndex);

        #endregion

        #region FillRecordContainer

        // Enable container if we have a record selected
        if (state.SelectedGeneralRecord == null || state.SelectedDetails == null)
        {
            RecordContainerStatus.Visible = true;
            RecordContainer.Visible = false;
            return;
        }

        RecordContainerStatus.Visible = false;
        RecordContainer.Visible = true;

        var record = state.SelectedGeneralRecord;
        var cr = state.SelectedDetails;

        // Basic info
        RecordContainerName.Text = record.Name;
        RecordContainerAge.Text = record.Age.ToString();
        RecordContainerJob.Text = record.JobTitle; /* At some point in the future we might want to display the icon */
        RecordContainerGender.Text = record.Gender.ToString();
        RecordContainerSpecies.Text = record.Species;
        RecordContainerWeight.Text = $"{cr.Weight} ({UnitConversion.GetImperialDisplayMass(cr.Weight)})";
        RecordContainerWeightRow.Visible = _type is RecordConsoleType.Medical or RecordConsoleType.Admin;
        RecordContainerContactName.SetValue(cr.EmergencyContactName);
        RecordContainerContactName.Visible = _type is not RecordConsoleType.Security;

        RecordContainerEmployment.Visible = false;
        RecordContainerMedical.Visible = false;
        RecordContainerSecurity.Visible = false;

        switch (_type)
        {
            case RecordConsoleType.Employment:
                SetEntries(cr.EmploymentEntries);
                UpdateRecordBoxEmployment(cr);
                break;
            case RecordConsoleType.Medical:
                SetEntries(cr.MedicalEntries);
                UpdateRecordBoxMedical(cr, state.SelectedSex);
                break;
            case RecordConsoleType.Security:
                SetEntries(cr.SecurityEntries);
                UpdateRecordBoxSecurity(cr, record, state.SelectedSecurityStatus);
                break;
            case RecordConsoleType.Admin:
                UpdateRecordBoxEmployment(cr);
                UpdateRecordBoxMedical(cr, state.SelectedSex);
                UpdateRecordBoxSecurity(cr, record, state.SelectedSecurityStatus);
                switch ((RecordConsoleType) RecordEntryViewType.SelectedId)
                {
                case RecordConsoleType.Employment:
                    SetEntries(cr.EmploymentEntries, true);
                    break;
                case RecordConsoleType.Medical:
                    SetEntries(cr.MedicalEntries, true);
                    break;
                case RecordConsoleType.Security:
                    SetEntries(cr.SecurityEntries, true);
                    break;
                }
                break;
        }

        #endregion

    }

    private void SetEntries(List<PlayerProvidedCharacterRecords.RecordEntry> entries, bool addIndex = false)
    {
        _entries = entries;
        RecordEntryList.Clear();
        var i = 0;
        foreach (var entry in entries)
        {
            RecordEntryList.AddItem(addIndex ? $"({i.ToString()}) " + entry.Title : entry.Title);
            ++i;
        }
    }

    private void UpdateRecordBoxEmployment(PlayerProvidedCharacterRecords record)
    {
        RecordContainerEmployment.Visible = true;
        RecordContainerWorkAuth.Text = record.HasWorkAuthorization
            ? Loc.GetString("cd-character-records-viewer-yes")
            : Loc.GetString("cd-character-records-viewer-no");
    }

    private void UpdateRecordBoxMedical(PlayerProvidedCharacterRecords cr, Content.Shared.Humanoid.Sex? sex)
    {
        RecordContainerMedical.Visible = true;
        RecordContainerAllergies.SetValue(cr.Allergies);
        RecordContainerDrugAllergies.SetValue(cr.DrugAllergies);
        RecordContainerPostmortem.SetValue(cr.PostmortemInstructions);
        RecordContainerSex.Text = sex?.ToString() ?? string.Empty;
    }

    private void UpdateRecordBoxSecurity(PlayerProvidedCharacterRecords details, GeneralStationRecord record, (SecurityStatus, string?)? criminal)
    {
        RecordContainerSecurity.Visible = true;
        RecordContainerIdentFeatures.SetValue(details.IdentifyingFeatures);
        RecordContainerFingerprint.Text = record.Fingerprint ?? Loc.GetString("cd-character-records-viewer-unknown");
        RecordContainerDNA.Text = record.DNA ?? Loc.GetString("cd-character-records-viewer-unknown");

        RecordContainerWantedReason.Visible = false;
        if (criminal != null)
        {
            var (stat, reason) = criminal.Value;
            StatusOptionButton.Select((int)stat);
            RecordContainerWantedReason.Text = reason;
            RecordContainerWantedReason.Visible = reason != null;
        }
    }

    private void SetStatusWithReason(SecurityStatus status)
    {
        if (_wantedReasonDialog != null)
        {
            _wantedReasonDialog.MoveToFront();
            return;
        }

        const string field = "reason";
        var title = Loc.GetString("criminal-records-status-" + status.ToString().ToLower());
        var placeholder = Loc.GetString("cd-character-records-viewer-setwanted-placeholder");
        var prompt = Loc.GetString("criminal-records-console-reason");
        var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt, placeholder);
        var entries = new List<QuickDialogEntry>() { entry };
        _wantedReasonDialog = new DialogWindow(title, entries);

        _wantedReasonDialog.OnConfirmed += responses =>
        {
            var reason = responses[field];
            if (reason.Length < 1 || reason.Length > SecurityWantedStatusMaxLength)
                return;

            OnSetSecurityStatus?.Invoke(status, reason);
        };

        _wantedReasonDialog.OnClose += () => { _wantedReasonDialog = null; };
    }
    public bool IsSecurity()
    {
        return _type == RecordConsoleType.Security || _type == RecordConsoleType.Admin;
    }

    public void SetSecurityStatusEnabled(bool setting)
    {
        for (var i = 0; i < StatusOptionButton.ItemCount; ++i)
        {
            StatusOptionButton.SetItemDisabled(i, !setting);
        }
    }
}

