using Content.Shared._Sirena.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        public Action<string>? OnFlavorTextChanged;
        public Action<ErpStatus>? OnErpStatusChanged; // RS14

        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();
            CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
            CFlavorTextInput.OnTextChanged  += _ => FlavorTextChanged();
            // RS14-start
            CErpStatusOption.AddItem(loc.GetString("humanoid-erp-status-no"), (int)ErpStatus.No);
            CErpStatusOption.AddItem(loc.GetString("humanoid-erp-status-partial"), (int)ErpStatus.Partial);
            CErpStatusOption.AddItem(loc.GetString("humanoid-erp-status-full"), (int)ErpStatus.Full);
            CErpStatusOption.OnItemSelected += args =>
            {
                CErpStatusOption.SelectId(args.Id);
                OnErpStatusChanged?.Invoke((ErpStatus)args.Id);
            };
            // RS14-end
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
        }

        // RS14-start
        public void SetErpStatus(ErpStatus status)
        {
            CErpStatusOption.SelectId((int)status);
        }
        // RS14-end
    }
}
