using System.Linq;
using System.Text.RegularExpressions;
using Content.Client.Stylesheets;
using Content.Shared._Corvax.TTS;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Corvax.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public event Action<ProtoId<TTSVoicePrototype>>? OnVoiceSelected;
    public event Action<ProtoId<TTSVoicePrototype>>? OnPreviewRequested;

    private List<TTSVoicePrototype> _allVoices = new();
    private List<TTSVoicePrototype> _filteredVoices = new();
    private Dictionary<string, List<TTSVoicePrototype>> _categorizedVoices = new();
    private ProtoId<TTSVoicePrototype>? _selectedVoiceId;

    private static readonly Regex CategoryRegex = new(@"^(.*?)\s*\(([^)]+)\)\s*$", RegexOptions.Compiled);

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LoadVoices();
        SearchEdit.OnTextChanged += OnSearchChanged;
    }

    private void LoadVoices()
    {
        foreach (var voice in _allVoices)
        {
            var name = Loc.GetString(voice.Name);
            var category = Loc.GetString("humanoid-profile-editor-voice-other");

            var match = CategoryRegex.Match(name);
            if (match.Success)
            {
                category = match.Groups[2].Value.Trim();
            }

            if (!_categorizedVoices.ContainsKey(category))
                _categorizedVoices[category] = new List<TTSVoicePrototype>();

            _categorizedVoices[category].Add(voice);
        }

        CategoriesContainer.RemoveAllChildren();

        foreach (var category in _categorizedVoices.Keys.OrderBy(k => k))
        {
            var button = new Button
            {
                Text = category,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-category-tooltip", ("category", category)),
                HorizontalExpand = true,
            };

            button.OnPressed += _ =>
            {
                SearchEdit.Text = category;
                UpdateResults();
            };

            CategoriesContainer.AddChild(button);
        }

        UpdateResults();
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        UpdateResults();
    }

    private void UpdateResults()
    {
        VoicesGrid.RemoveAllChildren();
        _filteredVoices.Clear();

        var searchText = SearchEdit.Text.ToLowerInvariant();

        foreach (var voice in _allVoices)
        {
            var name = Loc.GetString(voice.Name).ToLowerInvariant();

            if (string.IsNullOrEmpty(searchText) ||
                name.Contains(searchText) ||
                voice.ID.Contains(searchText, StringComparison.InvariantCultureIgnoreCase))
            {
                _filteredVoices.Add(voice);
            }
        }

        foreach (var voice in _filteredVoices)
        {
            var displayName = Loc.GetString(voice.Name);

            var voiceContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            };

            var selectButton = new Button
            {
                Text = displayName,
                ToolTip = voice.ID,
                HorizontalExpand = true,
                StyleClasses = { StyleClass.ButtonOpenRight }
            };

            selectButton.OnPressed += _ => { OnVoiceSelected?.Invoke(voice.ID); };

            var previewButton = new Button
            {
                Text = Loc.GetString("humanoid-profile-editor-voice-play"),
                MinWidth = 30,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-tooltip-play"),
                StyleClasses = { StyleClass.ButtonOpenLeft }
            };

            previewButton.OnPressed += _ => { OnPreviewRequested?.Invoke(voice.ID); };

            if (voice.ID == _selectedVoiceId)
            {
                selectButton.AddStyleClass(StyleClass.Negative);
                previewButton.AddStyleClass(StyleClass.Negative);
            }

            voiceContainer.AddChild(selectButton);
            voiceContainer.AddChild(previewButton);

            VoicesGrid.AddChild(voiceContainer);
        }

        ResultsLabel.Text = Loc.GetString("humanoid-profile-editor-voice-match",
            ("filtered", _filteredVoices.Count), ("all", _allVoices.Count));
    }

    public void UpdateControls(HumanoidCharacterProfile? profile, Sex sex, ProtoId<SpeciesPrototype> species)
    {
        if (profile == null)
            return;

        _selectedVoiceId = profile.TTSVoice;

        _allVoices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(voice => HumanoidCharacterProfile.CanHaveVoice(voice, sex, species))
            .OrderBy(voice => Loc.GetString(voice.Name))
            .ToList();

        _categorizedVoices.Clear();
        LoadVoices();
    }

    public void SetSelectedVoice(ProtoId<TTSVoicePrototype> voiceId)
    {
        _selectedVoiceId = voiceId;
        UpdateResults();
    }
}
