using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared._Corvax.TTS;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Corvax.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public event Action<ProtoId<TTSVoicePrototype>>? OnVoiceSelected;
    public event Action<ProtoId<TTSVoicePrototype>>? OnPreviewRequested;

    private List<TTSVoicePrototype> _allVoices = new();
    private ProtoId<TTSVoicePrototype>? _selectedVoiceId;
    private LocId? _selectedCategory;

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchEdit.OnTextChanged += OnSearchChanged;
    }

    private void LoadCategories()
    {
        CategoriesContainer.RemoveAllChildren();

        AddCategoryButton(
            Loc.GetString("humanoid-profile-editor-voice-all"),
            null);

        var categories = _allVoices
            .Select(voice => voice.Category)
            .Distinct()
            .OrderBy(category => Loc.GetString(category));

        foreach (var category in categories)
        {
            AddCategoryButton(Loc.GetString(category), category);
        }

        UpdateResults();
    }

    private void AddCategoryButton(string name, LocId? category)
    {
        var button = new Button
        {
            Text = name,
            ToolTip = category != null
                ? Loc.GetString("humanoid-profile-editor-voice-category-tooltip", ("category", name))
                : null,
            HorizontalExpand = true,
        };

        button.OnPressed += _ =>
        {
            _selectedCategory = category;
            UpdateResults();
        };

        CategoriesContainer.AddChild(button);
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        UpdateResults();
    }

    private void UpdateResults()
    {
        VoicesGrid.RemoveAllChildren();

        var searchText = SearchEdit.Text.ToLowerInvariant();

        var voices = _allVoices.Where(voice =>
        {
            if (_selectedCategory != null && voice.Category != _selectedCategory)
                return false;

            if (string.IsNullOrEmpty(searchText))
                return true;

            var name = Loc.GetString(voice.Name).ToLowerInvariant();
            var category = Loc.GetString(voice.Category).ToLowerInvariant();

            return name.Contains(searchText) ||
                   category.Contains(searchText) ||
                   voice.ID.Contains(searchText, StringComparison.InvariantCultureIgnoreCase);
        }).ToList();

        foreach (var voice in voices)
        {
            var displayName = Loc.GetString(voice.Name);

            var voiceContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            };

            var selectButton = new Button
            {
                Text = displayName,
                ToolTip = voice.ID,
                HorizontalExpand = true,
                StyleClasses = { StyleClass.ButtonOpenRight }
            };

            selectButton.OnPressed += _ => OnVoiceSelected?.Invoke(voice.ID);

            var previewButton = new Button
            {
                Text = Loc.GetString("humanoid-profile-editor-voice-play"),
                MinWidth = 30,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-tooltip-play"),
                StyleClasses = { StyleClass.ButtonOpenLeft }
            };

            previewButton.OnPressed += _ => OnPreviewRequested?.Invoke(voice.ID);

            if (voice.ID == _selectedVoiceId)
            {
                selectButton.AddStyleClass(StyleClass.Negative);
                previewButton.AddStyleClass(StyleClass.Negative);
            }

            voiceContainer.AddChild(selectButton);
            voiceContainer.AddChild(previewButton);

            VoicesGrid.AddChild(voiceContainer);
        }

        ResultsLabel.Text = Loc.GetString("humanoid-profile-editor-voice-match",
            ("filtered", voices.Count), ("all", _allVoices.Count));
    }

    public void UpdateControls(HumanoidCharacterProfile? profile, Sex sex, ProtoId<SpeciesPrototype> species)
    {
        if (profile == null)
            return;

        _selectedVoiceId = profile.TTSVoice;

        _allVoices = TTSVoiceHelper
            .GetValidVoices(_prototypeManager, sex, species)
            .OrderBy(voice => Loc.GetString(voice.Name))
            .ToList();

        LoadCategories();
    }

    public void SetSelectedVoice(ProtoId<TTSVoicePrototype> voiceId)
    {
        _selectedVoiceId = voiceId;
        UpdateResults();
    }
}
