using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RedStar.Xenobiology.UI.Scanner;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyScannerWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _systems = default!;

    private EntProtoId[]? _displayedMutations;
    private readonly List<Label> _mutationProgressLabels = [];
    private static readonly Color Positive = Color.FromHex("#9FD6AD");

    public XenobiologyScannerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("slime-scanner-title");
        GrowthBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Positive.WithAlpha(0.7f) };
        Populate(null, Loc.GetString("slime-scan-card-awaiting-scan"));
    }

    public void Populate(XenobiologyScannerScannedMessage message)
    {
        Populate(message.Data);
    }

    private void Populate(XenobiologyScanData? scan, string? placeholder = null, EntityUid? specimen = null)
    {
        Card.Visible = scan != null;
        Placeholder.Visible = scan == null;
        Placeholder.SetMessage(placeholder ?? string.Empty);
        PortraitPanel.Visible = scan != null && (specimen != null || scan.Value.Prototype != null);
        Portrait.Visible = specimen != null;
        PortraitIcon.Visible = specimen == null;
        if (Portrait.Entity?.Owner != specimen)
            Portrait.SetEntity(specimen);
        if (scan is not { } data)
            return;

        SpecimenName.Text = data.TargetName;
        StageValue.Text = data.Development is { IsJuvenile: true }
            ? Loc.GetString("slime-scan-stage-baby")
            : Loc.GetString("slime-scan-stage-adult");
        PortraitIcon.Texture = data.Prototype is { } prototype
            ? _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(prototype.Id).Default
            : null;
        var development = data.Development?.Progress ?? 0f;
        GrowthValue.Text = development.ToString("P0");
        GrowthBar.Value = Math.Clamp(development, 0f, 1f);
        HungerSection.Visible = data.Nutrition != null;
        HungerValue.Text = data.Nutrition?.Hunger.ToString("0.#") ?? string.Empty;

        if (_displayedMutations != null && _displayedMutations.SequenceEqual(data.Mutations.Select(entry => entry.Target)))
        {
            for (var i = 0; i < data.Mutations.Length; i++)
            {
                _mutationProgressLabels[i].Text = data.Mutations[i].Progress.ToString("P0");
            }

            return;
        }

        MutationList.RemoveAllChildren();
        _mutationProgressLabels.Clear();
        _displayedMutations = data.Mutations.Select(entry => entry.Target).ToArray();
        if (data.Mutations.Length == 0)
        {
            MutationList.AddChild(new Label { Text = Loc.GetString("slime-scanner-none"), StyleClasses = { "LabelSubText" } });
            return;
        }

        foreach (var mutation in data.Mutations)
        {
            var row = new BoxContainer { HorizontalExpand = true, SeparationOverride = 8 };
            row.AddChild(new TextureRect
            {
                Texture = _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(mutation.Target.Id).Default,
                SetSize = new Vector2(24, 24),
                Stretch = TextureRect.StretchMode.KeepAspectCentered
            });
            row.AddChild(new Label { Text = NameOf(mutation.Target), HorizontalExpand = true, ClipText = true });
            var readiness = new Label { Text = mutation.Progress.ToString("P0") };
            _mutationProgressLabels.Add(readiness);
            row.AddChild(readiness);
            MutationList.AddChild(row);
        }
    }

    private string NameOf(EntProtoId id) => _prototypes.TryIndex(id, out var prototype) ? prototype.Name : id.Id;
}
