using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RedStar.DiscordAuth;

[GenerateTypedNameReferences]
public sealed partial class DiscordAuthWindow : FancyWindow
{
    public DiscordAuthWindow(
        string link,
        Texture? qrCode,
        Action checkStatus)
    {
        RobustXamlLoader.Load(this);

        Description.SetMessage(Loc.GetString("discord-auth-description"));

        Link.Text = link;

        QrCode.Texture = qrCode;
        QrCode.Visible = qrCode != null;

        OpenBrowser.OnPressed += _ =>
            IoCManager.Resolve<IUriOpener>().OpenUri(link);

        Check.OnPressed += _ => checkStatus();

        Status.Text = Loc.GetString("discord-auth-status-waiting");
    }

    public void SetLinked()
    {
        Status.Text = Loc.GetString("discord-auth-status-linked");

        OpenBrowser.Disabled = true;
        Check.Disabled = true;
    }
}
