- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtElegantMaid
  name: elegant maid uniform
  description: Call me master and bring me some beer.
  components:
  - type: Sprite
    sprite: _Corvax/Clothing/Uniforms/Jumpskirts/Service/elegantmaid.rsi
  - type: Clothing
    sprite: _Corvax/Clothing/Uniforms/Jumpskirts/Service/elegantmaid.rsi