using System.Linq;
using Content.Client._Corvax.TTS;
using Content.Client.Options.UI;
using Content.Shared._Corvax.CCCVars;
using Content.Shared._Corvax.TTS.Enums;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._Corvax.Options.UI.Tabs;

/// <summary>
/// TTS Control with all settings
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TTSControl : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly Dictionary<string, Slider> _channelSliders = new();
    private OptionsTabControlRow _controlRow = default!;

    public const float TtsMultiplier = 3f;

    public TTSControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Initialize(OptionsTabControlRow controlRow)
    {
        _controlRow = controlRow;

        InitializeControls();
        PopulateVoiceEffectOptions();
        BuildRadioChannelControls();

        _controlRow.AddOption(new OptionRadioChannelVolumes(_controlRow, _cfg, _channelSliders));
    }

    private void InitializeControls()
    {
        // TTS Volume
        _controlRow.AddOptionPercentSlider(
            CCCVars.TTSVolume,
            SliderVolumeTts,
            scale: TtsMultiplier);

        // TTS Radio Volume
        _controlRow.AddOptionPercentSlider(
            CCCVars.TTSRadioVolume,
            SliderVolumeTtsRadio,
            scale: TtsMultiplier);
    }

    private void PopulateVoiceEffectOptions()
    {
        VoiceEffectOption.Clear();

        foreach (var preset in Enum.GetValues<TTSVoiceEffectPreset>())
        {
            var displayName = Loc.GetString($"tts-efx-effect-{preset.ToString().ToLowerInvariant()}");
            VoiceEffectOption.AddItem(displayName, (int)preset);
        }

        var currentValue = _cfg.GetCVar(CCCVars.TTSVoiceEffect);
        VoiceEffectOption.SelectId(currentValue);

        VoiceEffectOption.OnItemSelected += OnVoiceEffectSelected;
    }

    private void OnVoiceEffectSelected(OptionButton.ItemSelectedEventArgs args)
    {
        var preset = (TTSVoiceEffectPreset)args.Id;
        VoiceEffectOption.SelectId(args.Id);

        _cfg.SetCVar(CCCVars.TTSVoiceEffect, (ushort)preset);
        _cfg.SaveToFile();
    }

    private void BuildRadioChannelControls()
    {
        var channels = _prototypeManager
            .EnumeratePrototypes<RadioChannelPrototype>()
            .OrderBy(channel => channel.LocalizedName, StringComparer.CurrentCulture)
            .ThenBy(channel => channel.ID, StringComparer.Ordinal);

        foreach (var channel in channels)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1)
            };

            row.AddChild(new Label
            {
                Text = channel.LocalizedName,
                MinWidth = 200,
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = channel.Color
            });

            var slider = new Slider
            {
                MinValue = 0f,
                MaxValue = 1f,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            };

            var valueLabel = new Label
            {
                MinWidth = 48,
                Align = Label.AlignMode.Right,
                Margin = new Thickness(8, 0, 4, 0),
                VerticalAlignment = VAlignment.Center
            };

            slider.OnValueChanged += _ => valueLabel.Text = FormatPercent(slider.Value);
            valueLabel.Text = FormatPercent(slider.Value);

            row.AddChild(slider);
            row.AddChild(valueLabel);

            RadioChannelsContainer.AddChild(row);
            _channelSliders[channel.ID] = slider;
        }
    }

    private static string FormatPercent(float value)
    {
        return Loc.GetString("ui-options-value-percent", ("value", value));
    }
}

public sealed class OptionRadioChannelVolumes : BaseOptionCVar<string>
{
    private readonly Dictionary<string, Slider> _sliders;

    protected override string Value
    {
        get => TTSRadioVolumes.Serialize(
            _sliders.Select(pair => new KeyValuePair<string, float>(pair.Key, pair.Value.Value)));
        set
        {
            var volumes = TTSRadioVolumes.Parse(value);

            foreach (var (channel, slider) in _sliders)
            {
                slider.Value = volumes.GetValueOrDefault(channel, TTSRadioVolumes.FullVolume);
            }
        }
    }

    public OptionRadioChannelVolumes(
        OptionsTabControlRow controller,
        IConfigurationManager cfg,
        Dictionary<string, Slider> sliders)
        : base(controller, cfg, CCCVars.TTSRadioChannelVolumes)
    {
        _sliders = sliders;

        foreach (var slider in _sliders.Values)
        {
            slider.OnValueChanged += _ => ValueChanged();
        }
    }
}
