using Content.Shared._RedStar.Xenobiology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RedStar.Xenobiology.UI;

/// <summary>
/// Displays the properties of a cell in xenobiology machine windows.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CellInfoControl : Control
{
    [Dependency] private IEntityManager _entity = default!;

    private readonly CellSystem _cell;
    private string _labelPrefix = string.Empty;

    public CellInfoControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _cell = _entity.System<CellSystem>();
    }

    public void SetLabelPrefix(string prefix)
    {
        _labelPrefix = prefix;
        TraitsLabel.Text = Loc.GetString($"{prefix}-cell-traits-label");
    }

    public void SetCell(Cell cell)
    {
        CellStabilityLabel.Visible = true;
        TraitsLabel.Visible = true;
        CellTraitsText.Visible = true;

        CellNameLabel.Text = cell.Name;
        CellStabilityLabel.Text = Loc.GetString($"{_labelPrefix}-cell-stability-label",
            ("stability", Math.Round(cell.Stability * 100f, 3)));
        CellCostLabel.Text = Loc.GetString($"{_labelPrefix}-cell-cost-label", ("cost", cell.Cost));
        SetMarkup(CellTraitsText, _cell.GetCellTraitsString(cell.Traits));
    }

    public void SetPreview(int cost)
    {
        CellStabilityLabel.Visible = false;
        TraitsLabel.Visible = false;
        CellTraitsText.Visible = false;

        CellNameLabel.Text = "???";
        CellCostLabel.Text = Loc.GetString($"{_labelPrefix}-cell-cost-label", ("cost", cost));
    }

    private static void SetMarkup(RichTextLabel label, string message)
    {
        if (FormattedMessage.TryFromMarkup(message, out var markup))
            label.SetMessage(markup);
        else
            label.SetMessage(message);
    }
}
