using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology;
using Content.Shared._RedStar.Xenobiology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class CellSequencerWindow : FancyWindow
{
    public event Action? OnServerSelection;
    public event Action<int?, int, NetEntity?>? OnAdd;
    public event Action<int?, bool, int, NetEntity?>? OnRemove;
    public event Action<int?>? OnPrint;

    private CellEntryControl? _sequencerEntry;
    private IReadOnlyList<Cell> _insideCells = [];
    private IReadOnlyList<CellEntry> _remoteCells = [];
    private int _material;
    private bool _hasContainer;
    private bool _connected;
    private int _dishRevision;
    private NetEntity? _dish;

    private bool SelectionIsRemote => _sequencerEntry is { Remote: true };
    private Cell? SelectedCell => _sequencerEntry?.Cell;
    private bool HasMaterial => SelectedCell is { } cell && cell.Cost <= _material;

    public CellSequencerWindow()
    {
        RobustXamlLoader.Load(this);
        CellInfo.SetLabelPrefix("cell-sequencer-menu");
        ServerButton.OnPressed += _ => OnServerSelection?.Invoke();

        AddButton.OnPressed += _ => OnAdd?.Invoke(_sequencerEntry?.Id, _dishRevision, _dish);
        RemoveButton.OnPressed += _ =>
        {
            OnRemove?.Invoke(_sequencerEntry?.Id, _sequencerEntry?.Remote ?? false, _dishRevision, _dish);
            SelectedCellEntry(null);
        };
        ReplaceButton.OnPressed += _ => OnPrint?.Invoke(_sequencerEntry?.Id);
    }

    public void SetEntity(EntityUid owner)
    {
        MaterialsList.SetOwner(owner);
    }

    public void UpdateState(CellSequencerUiState state)
    {
        _material = state.Material;
        _hasContainer = state.HasContainer;
        _connected = state.Connected;
        _dishRevision = state.DishRevision;

        var insideChanged = _dish != state.Dish || !SameCells(_insideCells, state.InsideCells);
        var remoteChanged = !SameEntries(_remoteCells, state.RemoteCells);
        _dish = state.Dish;

        var selectedId = _sequencerEntry?.Id;
        var selectedRemote = SelectionIsRemote;
        var selectionChanged = selectedId is not null &&
            (selectedRemote ? remoteChanged : insideChanged);
        CellEntryControl? restored = null;

        if (insideChanged)
        {
            _insideCells = state.InsideCells.ToArray();
            InsideCellContainer.RemoveAllChildren();
            for (var index = 0; index < state.InsideCells.Length; index++)
            {
                var entry = new CellEntryControl(state.InsideCells[index], false, index);
                entry.OnSelect += SelectedCellEntry;
                InsideCellContainer.AddChild(entry);
                if (!selectedRemote && selectedId == index)
                    restored = entry;
            }
        }

        if (remoteChanged)
        {
            _remoteCells = state.RemoteCells.ToArray();
            RemoteCellContainer.RemoveAllChildren();
            foreach (var savedCell in state.RemoteCells)
            {
                var entry = new CellEntryControl(savedCell.Cell, true, savedCell.Id);
                entry.OnSelect += SelectedCellEntry;
                RemoteCellContainer.AddChild(entry);
                if (selectedRemote && selectedId == savedCell.Id)
                    restored = entry;
            }
        }

        if (selectionChanged)
        {
            _sequencerEntry = null;
            SelectedCellEntry(restored);
        }
        else
        {
            UpdateButtonState();
        }
    }

    private static bool SameCells(IReadOnlyList<Cell> left, IReadOnlyList<Cell> right)
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (!left[i].Equals(right[i]))
                return false;
        }

        return true;
    }

    private static bool SameEntries(IReadOnlyList<CellEntry> left, IReadOnlyList<CellEntry> right)
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (left[i].Id != right[i].Id || !left[i].Cell.Equals(right[i].Cell))
                return false;
        }

        return true;
    }

    private void SelectedCellEntry(CellEntryControl? entry)
    {
        _sequencerEntry?.SetState(true);
        _sequencerEntry = entry;
        _sequencerEntry?.SetState(false);
        CellInfo.Visible = SelectedCell is not null;
        NoSelectedLabel.Visible = SelectedCell is null;
        if (SelectedCell is { } cell)
            CellInfo.SetCell(cell);
        UpdateButtonState();
    }

    private void UpdateButtonState()
    {
        AddButton.Disabled = !_connected || SelectedCell is null || SelectionIsRemote;
        RemoveButton.Disabled = SelectedCell is null || (SelectionIsRemote && !_connected);
        ReplaceButton.Disabled = !SelectionIsRemote || !HasMaterial || !_hasContainer;
    }
}
