using Content.Shared._RedStar.Xenobiology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class CellEntryControl : Control
{
    public readonly Cell Cell;
    public readonly bool Remote;
    public readonly int Id;
    public event Action<CellEntryControl>? OnSelect;

    public CellEntryControl(Cell cell, bool remote, int id)
    {
        RobustXamlLoader.Load(this);
        Cell = cell;
        Remote = remote;
        Id = id;

        CellNameLabel.Text = cell.Name;
        Color.ModulateSelfOverride = cell.Color;

        Button.OnPressed += _ => OnSelect?.Invoke(this);
    }

    public void SetState(bool value)
    {
        Button.Disabled = !value;
    }
}
