using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology;
using Content.Shared._RedStar.Xenobiology.Systems;
using Content.Shared._RedStar.Xenobiology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class CellularFusionWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;

    public event Action? OnServerSelection;
    public event Action<int, int>? OnSplice;

    private CellEntryControl? _selectedEntryA;
    private CellEntryControl? _selectedEntryB;
    private IReadOnlyList<CellEntry> _remoteCells = [];
    private int _material;
    private bool _spliceInProgress;
    private bool _showingResult;
    private TimeSpan _spliceStartTime;
    private double _spliceDuration;

    public CellularFusionWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CellInfo.SetLabelPrefix("cellular-fusion-menu");
        ServerButton.OnPressed += _ => OnServerSelection?.Invoke();

        SpliceButton.OnPressed += _ =>
        {
            if (_selectedEntryA is not { } cellA || _selectedEntryB is not { } cellB)
                return;

            OnSplice?.Invoke(cellA.Id, cellB.Id);
        };
    }

    public void SetEntity(EntityUid owner)
    {
        MaterialsList.SetOwner(owner);
    }

    public void UpdateState(CellularFusionUiState state)
    {
        _material = state.Material;
        RebuildEntriesIfChanged(state.RemoteCells);

        if (state.SpliceInProgress && !_spliceInProgress)
        {
            _spliceInProgress = true;
            _showingResult = false;
            if (_selectedEntryA is null || _selectedEntryB is null)
                CellInfo.SetPreview(state.SpliceCost);
        }
        else if (!state.SpliceInProgress && _spliceInProgress)
        {
            _spliceInProgress = false;
            if (state.LastResult is { } result)
                ShowResult(result);
            else
                ClearSelection();
        }
        else if (state.LastResult is { } result)
        {
            ShowResult(result);
        }

        if (_spliceInProgress)
        {
            _spliceDuration = state.SpliceDuration;
            _spliceStartTime = _timing.RealTime - TimeSpan.FromSeconds(
                Math.Max(0, state.SpliceDuration - state.SpliceRemaining));
        }

        SpliceProgressBar.Visible = _spliceInProgress;
        if (_spliceInProgress)
        {
            CellANoSelectedLabel.Visible = false;
            CellBNoSelectedLabel.Visible = false;
        }

        CellInfo.Visible = _spliceInProgress || _showingResult ||
            _selectedEntryA is not null && _selectedEntryB is not null;
        CellInfoContainer.Visible = CellInfo.Visible;
        SpliceButton.Disabled = _spliceInProgress || _showingResult ||
            _selectedEntryA is null || _selectedEntryB is null ||
            SharedCellSystem.GetMergedCost(_selectedEntryA.Cell, _selectedEntryB.Cell) > _material;

        if (!_spliceInProgress && !_showingResult)
            UpdateCellInfo();
    }

    private void RebuildEntriesIfChanged(IReadOnlyList<CellEntry> cells)
    {
        if (SameEntries(_remoteCells, cells))
            return;

        var selectedA = _selectedEntryA?.Id;
        var selectedB = _selectedEntryB?.Id;
        _selectedEntryA = null;
        _selectedEntryB = null;
        _remoteCells = cells.ToArray();

        CellContainerA.RemoveAllChildren();
        CellContainerB.RemoveAllChildren();
        foreach (var savedCell in cells)
        {
            var entryA = new CellEntryControl(savedCell.Cell, true, savedCell.Id);
            entryA.OnSelect += SelectedCellEntryA;
            CellContainerA.AddChild(entryA);
            if (selectedA == savedCell.Id)
            {
                _selectedEntryA = entryA;
                entryA.SetState(false);
            }

            var entryB = new CellEntryControl(savedCell.Cell, true, savedCell.Id);
            entryB.OnSelect += SelectedCellEntryB;
            CellContainerB.AddChild(entryB);
            if (selectedB != savedCell.Id)
                continue;

            _selectedEntryB = entryB;
            entryB.SetState(false);
        }

        CellANoSelectedLabel.Visible = !_showingResult && _selectedEntryA is null;
        CellBNoSelectedLabel.Visible = !_showingResult && _selectedEntryB is null;
    }

    private static bool SameEntries(IReadOnlyList<CellEntry> left, IReadOnlyList<CellEntry> right)
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (left[i].Id != right[i].Id || !left[i].Cell.Equals(right[i].Cell))
                return false;
        }

        return true;
    }

    private void ClearSelection()
    {
        _selectedEntryA?.SetState(true);
        _selectedEntryB?.SetState(true);
        _selectedEntryA = null;
        _selectedEntryB = null;
        _showingResult = false;
        CellANoSelectedLabel.Visible = true;
        CellBNoSelectedLabel.Visible = true;
        CellInfoContainer.Visible = false;
        SpliceButton.Disabled = true;
    }

    private void ShowResult(Cell cell)
    {
        _selectedEntryA?.SetState(true);
        _selectedEntryB?.SetState(true);
        _selectedEntryA = null;
        _selectedEntryB = null;
        _showingResult = true;
        CellANoSelectedLabel.Visible = false;
        CellBNoSelectedLabel.Visible = false;
        CellInfoContainer.Visible = true;
        CellInfo.SetCell(cell);
        SpliceButton.Disabled = true;
    }

    private void SelectedCellEntryA(CellEntryControl entry)
    {
        if (_spliceInProgress)
            return;

        SelectCellEntry(entry, ref _selectedEntryA);
        CellANoSelectedLabel.Visible = false;
        CellBNoSelectedLabel.Visible = _selectedEntryB is null;
        UpdateCellInfo();
    }

    private void SelectedCellEntryB(CellEntryControl entry)
    {
        if (_spliceInProgress)
            return;

        SelectCellEntry(entry, ref _selectedEntryB);
        CellANoSelectedLabel.Visible = _selectedEntryA is null;
        CellBNoSelectedLabel.Visible = false;
        UpdateCellInfo();
    }

    private void SelectCellEntry(CellEntryControl entry, ref CellEntryControl? previous)
    {
        previous?.SetState(true);
        entry.SetState(false);
        previous = entry;
        _showingResult = false;
    }

    private void UpdateCellInfo()
    {
        if (_selectedEntryA is not { } entryA || _selectedEntryB is not { } entryB)
        {
            CellInfoContainer.Visible = false;
            SpliceButton.Disabled = true;
            return;
        }

        var cost = SharedCellSystem.GetMergedCost(entryA.Cell, entryB.Cell);
        CellInfo.SetPreview(cost);
        CellInfo.Visible = true;
        CellInfoContainer.Visible = true;
        SpliceButton.Disabled = _spliceInProgress || cost > _material;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_spliceInProgress)
            return;

        var elapsed = (_timing.RealTime - _spliceStartTime).TotalSeconds;
        var progress = _spliceDuration > 0
            ? Math.Clamp(elapsed / _spliceDuration * 100.0, 0.0, 100.0)
            : 0;
        SpliceProgressBar.Value = (float)progress;
    }
}
