using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class SlimeScannerWindow : FancyWindow
{
    public SlimeScannerWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("slime-scanner-title");
    }

    public void Populate(SlimeScannerScannedMessage message)
    {
        Details.Populate(message.Data);
    }
}
