using System.Linq;
using System.Numerics;
using Content.Shared._RedStar.Xenobiology.Slimes;
using Content.Shared._RedStar.Xenobiology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class SlimeScanDetailsControl : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _systems = default!;

    private EntProtoId[]? _displayedMutations;
    private static readonly Color Positive = Color.FromHex("#9FD6AD");

    public SlimeScanDetailsControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        GrowthBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Positive.WithAlpha(0.7f) };
    }

    public void Populate(SlimeScanData? scan, string? placeholder = null, EntityUid? specimen = null)
    {
        Card.Visible = scan != null;
        Placeholder.Visible = scan == null;
        Placeholder.SetMessage(placeholder ?? string.Empty);
        PortraitPanel.Visible = scan != null && (specimen != null || scan.Value.Prototype != null);
        Portrait.Visible = specimen != null;
        PortraitIcon.Visible = specimen == null;
        var portraitEntity = scan != null ? specimen : null;
        if (Portrait.Entity?.Owner != portraitEntity)
            Portrait.SetEntity(portraitEntity);
        if (scan is not { } data)
            return;

        SpecimenName.FullText = data.TargetName;
        StageValue.Text = Loc.GetString(data.Stage == SlimeStage.Baby ? "slime-scan-stage-baby" : "slime-scan-stage-adult");
        PortraitIcon.Texture = data.Prototype is { } prototype
            ? _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(prototype.Id).Default
            : null;
        GrowthValue.Text = data.Growth.ToString("P0");
        GrowthBar.Value = Math.Clamp(data.Growth, 0f, 1f);
        HungerValue.Text = data.Hunger?.ToString("0.#") ?? Loc.GetString("slime-scanner-none");
        MutationChanceValue.Text = data.MutationChance.ToString("P0");

        // Keep controls stable during periodic scans; rebuild only when the mutation list changes.
        if (_displayedMutations != null && _displayedMutations.SequenceEqual(data.PotentialMutations))
            return;

        MutationList.RemoveAllChildren();
        _displayedMutations = data.PotentialMutations.ToArray();
        if (data.PotentialMutations.Length == 0)
        {
            MutationList.AddChild(new Label { Text = Loc.GetString("slime-scanner-none"), StyleClasses = { "LabelSubText" } });
            return;
        }

        foreach (var id in data.PotentialMutations)
        {
            var row = new BoxContainer { HorizontalExpand = true, SeparationOverride = 8 };
            row.AddChild(new TextureRect
            {
                Texture = _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(id.Id).Default,
                SetSize = new Vector2(24, 24),
                Stretch = TextureRect.StretchMode.KeepAspectCentered
            });
            row.AddChild(new XenobiologyNameLabel { FullText = NameOf(id) });
            MutationList.AddChild(row);
        }
    }

    private string NameOf(EntProtoId id) => _prototypes.TryIndex(id, out var prototype) ? prototype.Name : id.Id;

}
