using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class SlimeScanDetailsControl : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypes = default!;

    private EntProtoId[]? _displayedMutations;
    private static readonly Color Positive = Color.FromHex("#9FD6AD");
    private static readonly Color Caution = Color.FromHex("#E8C980");
    private static readonly Color Warning = Color.FromHex("#EC9C9C");

    public SlimeScanDetailsControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        EnhancedText.SetMessage(Loc.GetString("slime-scanner-extract-yield-enhanced"));
        EnhancedText.Modulate = Positive;
    }

    public void Populate(SlimeScanData? scan, string? placeholder = null, EntityUid? specimen = null)
    {
        Card.Visible = scan != null;
        Placeholder.Visible = scan == null;
        Placeholder.SetMessage(placeholder ?? string.Empty);
        PortraitPanel.Visible = scan != null && specimen != null;
        var portraitEntity = scan != null ? specimen : null;
        if (Portrait.Entity?.Owner != portraitEntity)
            Portrait.SetEntity(portraitEntity);
        if (scan is not { } data)
            return;

        SpecimenName.Text = data.TargetName;
        SpecimenName.ToolTip = data.TargetName;
        GrowthValue.Text = data.Growth.ToString("P0");
        GrowthBar.Value = Math.Clamp(data.Growth, 0f, 1f);
        HungerValue.Text = data.Hunger?.ToString("0.#") ?? Loc.GetString("slime-scanner-none");
        TemperamentValue.Text = TemperamentName(data.Temperament);
        TemperamentValue.FontColorOverride = data.Temperament switch
        {
            SlimeTemperament.Calm => Positive,
            SlimeTemperament.Restless => Caution,
            SlimeTemperament.Aggressive => Warning,
            _ => Color.White
        };
        CrowdingValue.Text = CrowdingName(data.Crowding);
        CrowdingValue.FontColorOverride = data.Crowding switch
        {
            SlimeCrowding.Low => Positive,
            SlimeCrowding.Crowded => Caution,
            SlimeCrowding.Severe => Warning,
            _ => Color.White
        };
        MutationChanceValue.Text = data.MutationChance.ToString("P0");
        EnhancedBanner.Visible = data.ExtractYieldEnhanced;

        // Keep controls stable during periodic scans; rebuild only when the mutation list changes.
        if (_displayedMutations != null && _displayedMutations.SequenceEqual(data.PotentialMutations))
            return;

        MutationList.RemoveAllChildren();
        _displayedMutations = data.PotentialMutations.ToArray();
        if (data.PotentialMutations.Length == 0)
        {
            MutationList.AddChild(new Label { Text = Loc.GetString("slime-scanner-none"), StyleClasses = { "LabelSubText" } });
            return;
        }

        foreach (var id in data.PotentialMutations)
        {
            var label = new RichTextLabel { HorizontalExpand = true };
            var message = new FormattedMessage();
            message.AddText("• " + NameOf(id));
            label.SetMessage(message);
            MutationList.AddChild(label);
        }
    }

    private string NameOf(EntProtoId id) => _prototypes.TryIndex(id, out var prototype) ? prototype.Name : id.Id;

    private static string TemperamentName(SlimeTemperament temperament) => Loc.GetString(temperament switch
    {
        SlimeTemperament.Calm => "slime-scanner-temperament-calm",
        SlimeTemperament.Restless => "slime-scanner-temperament-restless",
        SlimeTemperament.Aggressive => "slime-scanner-temperament-aggressive",
        _ => "slime-scanner-none"
    });

    private static string CrowdingName(SlimeCrowding crowding) => Loc.GetString(crowding switch
    {
        SlimeCrowding.Low => "slime-scanner-crowding-low",
        SlimeCrowding.Crowded => "slime-scanner-crowding-crowded",
        SlimeCrowding.Severe => "slime-scanner-crowding-severe",
        _ => "slime-scanner-none"
    });
}
