using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology.Components;
using Content.Shared._RedStar.Xenobiology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class XenobiologySampleAnalyzerWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _systems = default!;
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IGameTiming _timing = default!;

    public event Action? AnalyzeRequested;
    public event Action? ServerRequested;

    private XenobiologySampleAnalyzerUiState? _state;
    private readonly List<XenobiologyResearchEntryControl> _cards = new();
    private static readonly Color Accent = Color.FromHex("#9FD6AD");
    private readonly StyleBoxFlat _sampleFrame = new()
    {
        BackgroundColor = Color.FromHex("#20242B"),
        BorderColor = Color.FromHex("#414854"),
        BorderThickness = new Thickness(1)
    };

    public XenobiologySampleAnalyzerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        ServerName.FullText = Loc.GetString("xenobiology-analyzer-server-disconnected");
        SampleName.FullText = Loc.GetString("xenobiology-analyzer-sample-empty");
        TargetsHint.SetMessage(Loc.GetString("xenobiology-analyzer-no-server"));
        SampleFrame.PanelOverride = _sampleFrame;
        Progress.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Accent.WithAlpha(0.7f) };
        SampleEmpty.FontColorOverride = Color.FromHex("#AAB2BC");
        AnalyzeButton.OnPressed += _ => AnalyzeRequested?.Invoke();
        ServerButton.OnPressed += _ => ServerRequested?.Invoke();
    }

    public void UpdateState(XenobiologySampleAnalyzerUiState state)
    {
        ServerName.FullText = state.ServerName ?? Loc.GetString("xenobiology-analyzer-server-disconnected");
        TargetCount.Text = state.Targets.Length.ToString();
        ServerButton.Disabled = state.Status == XenobiologySampleStatus.Unpowered;
        AnalyzeButton.Disabled = state.Status != XenobiologySampleStatus.Ready;
        AnalyzeButton.Text = Loc.GetString(state.Status == XenobiologySampleStatus.Analyzing
            ? "xenobiology-analyzer-analyzing"
            : "xenobiology-analyzer-analyze-verb");
        var completed = state.Result != null && state.Status == XenobiologySampleStatus.Empty;
        AnalysisProgress.Visible = state.Status == XenobiologySampleStatus.Analyzing || completed;
        ProgressLabel.Text = Loc.GetString(completed
            ? "xenobiology-analyzer-analysis-completed"
            : "xenobiology-analyzer-analyzing");
        ProgressLabel.ToolTip = state.Result is { } result ? NameOf(result.Sample) : null;
        if (completed)
        {
            Progress.Value = 1;
            ProgressValue.Text = 1f.ToString("P0");
        }

        SampleIcon.Visible = state.SamplePrototype != null;
        SampleEmpty.Visible = !SampleIcon.Visible;
        _sampleFrame.BorderColor = state.Status is XenobiologySampleStatus.Ready or XenobiologySampleStatus.Analyzing
            ? Accent
            : Color.FromHex("#414854");
        if (state.SamplePrototype is { } sample)
        {
            SampleName.FullText = NameOf(sample);
            SampleIcon.Texture = _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(sample.Id).Default;
            if (state.Sample is { } net && _entities.TryGetEntity(net, out var uid) &&
                uid is { } local && !_entities.Deleted(local))
                SampleName.FullText = _entities.GetComponent<MetaDataComponent>(local).EntityName;
        }
        else
        {
            SampleName.FullText = Loc.GetString("xenobiology-analyzer-sample-empty");
            SampleIcon.Texture = null;
        }
        SampleStatus.SetMessage(completed && state.Result is { } receipt
            ? Loc.GetString("xenobiology-analyzer-complete", ("points", receipt.Reward))
            : Loc.GetString(state.Status switch
        {
            XenobiologySampleStatus.Empty => "xenobiology-analyzer-insert-hint",
            XenobiologySampleStatus.NoServer => "xenobiology-analyzer-no-server",
            XenobiologySampleStatus.Unpowered => "xenobiology-analyzer-unpowered",
            XenobiologySampleStatus.Ready => "xenobiology-analyzer-sample-matched",
            XenobiologySampleStatus.Analyzing => "xenobiology-analyzer-analysis-hint",
            _ => "xenobiology-analyzer-no-target"
        }));
        SampleStatus.Modulate = completed || state.Status == XenobiologySampleStatus.Ready ? Accent : Color.White;
        TargetsHint.Visible = state.Targets.Length == 0;
        TargetsHint.SetMessage(Loc.GetString(state.Status == XenobiologySampleStatus.NoServer
            ? "xenobiology-analyzer-no-server"
            : "xenobiology-analyzer-no-targets"));

        if (_state == null || !_state.Targets.SequenceEqual(state.Targets))
        {
            TargetCards.RemoveAllChildren();
            _cards.Clear();
            foreach (var target in state.Targets)
            {
                var card = new XenobiologyResearchEntryControl(target, NameOf(target.Sample),
                    _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(target.Sample.Id).Default);
                _cards.Add(card);
                TargetCards.AddChild(card);
            }
        }
        foreach (var card in _cards)
            card.UpdateState(state);
        _state = state;
        UpdateProgress();
    }

    private string NameOf(EntProtoId<SlimeExtractComponent> sample) =>
        _prototypes.TryIndex(sample, out var prototype) ? prototype.Name : sample.Id;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateProgress();
    }

    private void UpdateProgress()
    {
        if (_state is not { Status: XenobiologySampleStatus.Analyzing, AnalysisStart: { } start, AnalysisEnd: { } end })
            return;

        var duration = (end - start).TotalSeconds;
        var value = duration > 0 ? (float)Math.Clamp((_timing.CurTime - start).TotalSeconds / duration, 0, 1) : 1f;
        Progress.Value = value;
        var percentage = value.ToString("P0");
        if (ProgressValue.Text != percentage)
            ProgressValue.Text = percentage;
    }
}
