using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology.Components;
using Content.Shared._RedStar.Xenobiology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class XenobiologySampleAnalyzerWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _systems = default!;
    [Dependency] private IEntityManager _entities = default!;

    public event Action? AnalyzeRequested;
    public event Action? ServerRequested;

    private XenobiologySampleAnalyzerUiState? _state;
    private readonly List<XenobiologyResearchEntryControl> _cards = new();
    private static readonly Color Accent = Color.FromHex("#9FD6AD");
    private readonly StyleBoxFlat _sampleFrame = new()
    {
        BackgroundColor = Color.FromHex("#20242B"),
        BorderColor = Color.FromHex("#414854"),
        BorderThickness = new Thickness(1)
    };

    public XenobiologySampleAnalyzerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        ServerName.FullText = Loc.GetString("xenobiology-analyzer-server-disconnected");
        SampleName.FullText = Loc.GetString("xenobiology-analyzer-sample-empty");
        TargetsHint.SetMessage(Loc.GetString("xenobiology-analyzer-no-server"));
        SampleFrame.PanelOverride = _sampleFrame;
        SampleEmpty.FontColorOverride = Color.FromHex("#AAB2BC");
        AnalyzeButton.OnPressed += _ => AnalyzeRequested?.Invoke();
        ServerButton.OnPressed += _ => ServerRequested?.Invoke();
    }

    public void UpdateState(XenobiologySampleAnalyzerUiState state)
    {
        ServerName.FullText = state.ServerName ?? Loc.GetString("xenobiology-analyzer-server-disconnected");
        RemainingSamples.Text = Loc.GetString("xenobiology-analyzer-remaining-samples", ("count", state.RemainingSamples));
        ServerButton.Disabled = state.Status == XenobiologySampleStatus.Unpowered;
        AnalyzeButton.Disabled = state.Status != XenobiologySampleStatus.Ready;
        var completed = state.Result != null && state.Status == XenobiologySampleStatus.Empty;

        SampleIcon.Visible = state.SamplePrototype != null;
        SampleEmpty.Visible = !SampleIcon.Visible;
        _sampleFrame.BorderColor = state.Status == XenobiologySampleStatus.Ready
            ? Accent
            : Color.FromHex("#414854");
        if (state.SamplePrototype is { } sample)
        {
            SampleName.FullText = NameOf(sample);
            SampleIcon.Texture = _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(sample.Id).Default;
            if (state.Sample is { } net && _entities.TryGetEntity(net, out var uid) &&
                uid is { } local && !_entities.Deleted(local))
                SampleName.FullText = _entities.GetComponent<MetaDataComponent>(local).EntityName;
        }
        else
        {
            SampleName.FullText = Loc.GetString("xenobiology-analyzer-sample-empty");
            SampleIcon.Texture = null;
        }
        SampleStatus.SetMessage(completed && state.Result is { } receipt
            ? Loc.GetString("xenobiology-analyzer-complete", ("points", receipt.Reward))
            : Loc.GetString(state.Status switch
        {
            XenobiologySampleStatus.Empty => "xenobiology-analyzer-insert-hint",
            XenobiologySampleStatus.NoServer => "xenobiology-analyzer-no-server",
            XenobiologySampleStatus.Unpowered => "xenobiology-analyzer-unpowered",
            XenobiologySampleStatus.Ready => "xenobiology-analyzer-sample-matched",
            _ => "xenobiology-analyzer-no-target"
        }));
        SampleStatus.Modulate = completed || state.Status == XenobiologySampleStatus.Ready ? Accent : Color.White;
        TargetsHint.Visible = state.Targets.Length == 0;
        TargetsHint.SetMessage(Loc.GetString(state.Status == XenobiologySampleStatus.NoServer
            ? "xenobiology-analyzer-no-server"
            : "xenobiology-analyzer-no-targets"));

        if (_state == null || !_state.Targets.SequenceEqual(state.Targets))
        {
            TargetCards.RemoveAllChildren();
            _cards.Clear();
            foreach (var target in state.Targets)
            {
                var card = new XenobiologyResearchEntryControl(target, NameOf(target.Sample),
                    _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(target.Sample.Id).Default);
                _cards.Add(card);
                TargetCards.AddChild(card);
            }
        }
        foreach (var card in _cards)
        {
            card.UpdateState(state);
        }

        CompletedHint.Visible = state.CompletedTargets.Length == 0;
        if (_state == null || !_state.CompletedTargets.SequenceEqual(state.CompletedTargets))
        {
            CompletedEntries.RemoveAllChildren();
            foreach (var target in state.CompletedTargets.OrderBy(target => NameOf(target.Sample)))
            {
                AddCompletedEntry(target);
            }
        }
        _state = state;
    }

    private void AddCompletedEntry(XenobiologyResearchEntry target)
    {
        var name = NameOf(target.Sample);
        var entry = new Button
        {
            Disabled = true,
            HorizontalExpand = true,
            ToolTip = name
        };
        entry.AddStyleClass("ButtonSquare");
        var content = new BoxContainer { SeparationOverride = 8, Margin = new Thickness(4) };
        content.AddChild(new TextureRect
        {
            Texture = _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(target.Sample.Id).Default,
            SetSize = new Vector2(32, 32),
            Stretch = TextureRect.StretchMode.KeepAspectCentered
        });
        var details = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center
        };
        details.AddChild(new XenobiologyNameLabel { FullText = name, StyleClasses = { "LabelSubText" } });
        details.AddChild(new Label
        {
            Text = Loc.GetString("xenobiology-analyzer-reward", ("points", target.Reward)),
            FontColorOverride = Accent,
            StyleClasses = { "LabelSubText" }
        });
        content.AddChild(details);
        entry.AddChild(content);
        CompletedEntries.AddChild(entry);
    }

    private string NameOf(EntProtoId<XenobiologySampleComponent> sample) =>
        _prototypes.TryIndex(sample, out var prototype) ? prototype.Name : sample.Id;

}
