using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology.Components;
using Content.Shared._RedStar.Xenobiology.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyDatabaseConsoleWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _systems = default!;

    private EntProtoId<XenobiologySampleComponent>? _selectedSample;
    private XenobiologyDatabaseEntry[] _entries = [];

    public XenobiologyDatabaseConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        UpdateDetails();
    }

    public void UpdateState(XenobiologyDatabaseConsoleUiState state)
    {
        ConnectionStatus.Text = state.Connected
            ? string.Empty
            : Loc.GetString("xenobiology-database-disconnected");
        CatalogCount.Text = Loc.GetString("xenobiology-database-count", ("count", state.Entries.Length));
        EmptyHint.Visible = state.Connected && state.Entries.Length == 0;
        EmptyHint.Text = Loc.GetString("xenobiology-database-empty");

        _entries = state.Connected
            ? state.Entries.OrderBy(entry => NameOf(entry.Sample), StringComparer.CurrentCultureIgnoreCase)
                .ThenBy(entry => entry.Sample.Id, StringComparer.Ordinal).ToArray()
            : [];
        if (_selectedSample is not { } selected || _entries.All(entry => entry.Sample != selected))
        {
            if (_entries.Length > 0)
                _selectedSample = _entries[0].Sample;
            else
                _selectedSample = null;
        }

        CatalogEntries.RemoveAllChildren();
        foreach (var entry in _entries)
        {
            var button = new Button { HorizontalExpand = true };
            var row = new BoxContainer { SeparationOverride = 8, Margin = new Thickness(4) };
            row.AddChild(new TextureRect
            {
                Texture = IconOf(entry.Sample),
                SetSize = new Vector2(32, 32),
                Stretch = TextureRect.StretchMode.KeepAspectCentered
            });
            row.AddChild(new Label
            {
                Text = NameOf(entry.Sample),
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true
            });
            button.AddChild(row);
            var sample = entry.Sample;
            button.OnPressed += _ =>
            {
                _selectedSample = sample;
                UpdateDetails();
            };
            CatalogEntries.AddChild(button);
        }

        UpdateDetails();
    }

    private void UpdateDetails()
    {
        XenobiologyDatabaseEntry? selected = null;
        foreach (var entry in _entries)
        {
            if (entry.Sample != _selectedSample)
                continue;

            selected = entry;
            break;
        }

        DetailsPanel.Visible = selected != null;
        if (selected is not { } record)
            return;

        DetailsIcon.Texture = IconOf(record.Sample);
        DetailsName.Text = NameOf(record.Sample);
        DetailsValue.Text = Loc.GetString("xenobiology-database-research-value", ("points", record.ResearchValue));
    }

    private string NameOf(EntProtoId<XenobiologySampleComponent> sample) =>
        _prototypes.TryIndex(sample, out var prototype) ? prototype.Name : sample.Id;

    private Robust.Client.Graphics.Texture IconOf(EntProtoId<XenobiologySampleComponent> sample) =>
        _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(sample.Id).Default;
}
