using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class XenobiologySampleAnalyzerWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _systems = default!;
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IGameTiming _timing = default!;

    public event Action? AnalyzeRequested;
    public event Action? ServerRequested;

    private XenobiologySampleAnalyzerUiState? _state;
    private static readonly Color Accent = Color.FromHex("#9FD6AD");

    public XenobiologySampleAnalyzerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        ServerName.Text = Loc.GetString("xenobiology-analyzer-server-disconnected");
        SampleName.Text = Loc.GetString("xenobiology-analyzer-sample-empty");
        TargetsHint.SetMessage(Loc.GetString("xenobiology-analyzer-no-server"));
        AnalyzeButton.OnPressed += _ => AnalyzeRequested?.Invoke();
        ServerButton.OnPressed += _ => ServerRequested?.Invoke();
    }

    public void UpdateState(XenobiologySampleAnalyzerUiState state)
    {
        ServerName.Text = state.ServerName ?? Loc.GetString("xenobiology-analyzer-server-disconnected");
        ServerName.ToolTip = ServerName.Text;
        ServerButton.Disabled = state.Status == XenobiologySampleStatus.Unpowered;
        AnalyzeButton.Disabled = state.Status != XenobiologySampleStatus.Ready;
        AnalyzeButton.Text = Loc.GetString(state.Status == XenobiologySampleStatus.Analyzing
            ? "xenobiology-analyzer-analyzing"
            : "xenobiology-analyzer-analyze-verb");
        AnalysisProgress.Visible = state.Status == XenobiologySampleStatus.Analyzing;

        SampleIcon.Visible = state.SamplePrototype != null;
        if (state.SamplePrototype is { } sample)
        {
            SampleName.Text = NameOf(sample);
            SampleIcon.Texture = _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(sample.Id).Default;
            if (state.Sample is { } net && _entities.TryGetEntity(net, out var uid) &&
                uid is { } local && !_entities.Deleted(local))
                SampleName.Text = _entities.GetComponent<MetaDataComponent>(local).EntityName;
        }
        else
        {
            SampleName.Text = Loc.GetString("xenobiology-analyzer-sample-empty");
            SampleIcon.Texture = null;
        }
        SampleName.ToolTip = SampleName.Text;
        SampleStatus.SetMessage(Loc.GetString(state.Status switch
        {
            XenobiologySampleStatus.Empty => "xenobiology-analyzer-insert-hint",
            XenobiologySampleStatus.NoServer => "xenobiology-analyzer-no-server",
            XenobiologySampleStatus.Unpowered => "xenobiology-analyzer-unpowered",
            XenobiologySampleStatus.Ready => "xenobiology-analyzer-sample-matched",
            XenobiologySampleStatus.Analyzing => "xenobiology-analyzer-analysis-hint",
            _ => "xenobiology-analyzer-no-target"
        }));
        SampleStatus.Modulate = state.Status == XenobiologySampleStatus.Ready ? Accent : Color.White;
        TargetsHint.Visible = state.Targets.Length == 0;
        TargetsHint.SetMessage(Loc.GetString(state.Status == XenobiologySampleStatus.NoServer
            ? "xenobiology-analyzer-no-server"
            : "xenobiology-analyzer-no-targets"));

        if (_state == null || !_state.Targets.SequenceEqual(state.Targets) ||
            _state.SamplePrototype != state.SamplePrototype || _state.Status != state.Status)
        {
            TargetCards.RemoveAllChildren();
            foreach (var target in state.Targets)
            {
                AddTargetCard(target, state);
            }
        }
        _state = state;
        UpdateProgress();
    }

    private void AddTargetCard(XenobiologyResearchEntry target, XenobiologySampleAnalyzerUiState state)
    {
        var matched = target.Sample == state.SamplePrototype &&
                      state.Status is XenobiologySampleStatus.Ready or XenobiologySampleStatus.Analyzing;
        var panel = new PanelContainer
        {
            SetWidth = 190,
            MinHeight = 200,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#20242B"),
                BorderColor = matched ? Accent : Color.FromHex("#414854"),
                BorderThickness = new Thickness(matched ? 2 : 1)
            }
        };
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 8,
            Margin = new Thickness(12),
            HorizontalExpand = true
        };
        content.AddChild(new TextureRect
        {
            Texture = _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(target.Sample.Id).Default,
            SetSize = new Vector2(64, 64),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = HAlignment.Center
        });
        var name = new RichTextLabel { MinHeight = 40, HorizontalExpand = true };
        var message = new FormattedMessage();
        message.AddText(NameOf(target.Sample));
        name.SetMessage(message);
        content.AddChild(name);
        content.AddChild(new Label
        {
            Text = Loc.GetString("xenobiology-analyzer-reward", ("points", target.Reward)),
            StyleClasses = { "LabelHeading" },
            FontColorOverride = Accent
        });
        content.AddChild(new Label
        {
            Text = Loc.GetString(matched
                ? state.Status == XenobiologySampleStatus.Analyzing
                    ? "xenobiology-analyzer-analyzing"
                    : "xenobiology-analyzer-card-matched"
                : "xenobiology-analyzer-card-available"),
            StyleClasses = { "LabelSubText" },
            FontColorOverride = matched ? Accent : Color.FromHex("#AAB2BC")
        });
        panel.AddChild(content);
        TargetCards.AddChild(panel);
    }

    private string NameOf(EntProtoId<SlimeExtractComponent> sample) =>
        _prototypes.TryIndex(sample, out var prototype) ? prototype.Name : sample.Id;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateProgress();
    }

    private void UpdateProgress()
    {
        if (_state is not { Status: XenobiologySampleStatus.Analyzing, AnalysisStart: { } start, AnalysisEnd: { } end })
            return;

        var duration = (end - start).TotalSeconds;
        var value = duration > 0 ? (float)Math.Clamp((_timing.CurTime - start).TotalSeconds / duration, 0, 1) : 1f;
        Progress.Value = value;
        ProgressValue.Text = value.ToString("P0");
    }
}
