using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyConsoleWindow : FancyWindow
{
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IEntitySystemManager _systems = default!;

    public event Action<NetEntity>? ScannerSelected;
    public event Action<NetEntity>? SlimeSelected;

    private XenobiologyConsoleUiState? _state;

    public XenobiologyConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        AddEmptyState(ScannerEntries, "xenobiology-console-no-scanners");
        AddEmptyState(SlimeEntries, "xenobiology-console-select-scanner");
        ScanDetails.Populate(null, Loc.GetString("xenobiology-console-select-scanner"));
    }

    public void UpdateState(XenobiologyConsoleUiState state)
    {
        LinkHint.Visible = state.LinkedScanners.Length == 0;
        ScannerCount.Text = state.LinkedScanners.Length.ToString();
        SlimeCount.Text = state.SelectedScanner != null ? state.DetectedSlimes.Length.ToString() : string.Empty;
        // Preserve scroll positions while only the analysis data changes.
        if (_state == null || _state.SelectedScanner != state.SelectedScanner ||
            !_state.LinkedScanners.SequenceEqual(state.LinkedScanners))
        {
            ScannerEntries.RemoveAllChildren();
            var defaultCount = state.LinkedScanners.Count(entry => entry.IsDefaultName);
            var defaultIndex = 0;
            foreach (var entry in state.LinkedScanners)
            {
                var name = entry.DisplayName;
                if (entry.IsDefaultName)
                {
                    defaultIndex++;
                    name = defaultCount > 1
                        ? Loc.GetString("xenobiology-console-scanner-numbered", ("number", defaultIndex))
                        : Loc.GetString("xenobiology-console-scanner-short");
                }
                AddScannerEntry(name, entry.DisplayName, entry.Entity == state.SelectedScanner,
                    () => ScannerSelected?.Invoke(entry.Entity));
            }

            if (state.LinkedScanners.Length == 0)
                AddEmptyState(ScannerEntries, "xenobiology-console-no-scanners");
        }

        if (_state == null || _state.SelectedScanner != state.SelectedScanner ||
            _state.SelectedSlime != state.SelectedSlime ||
            !_state.DetectedSlimes.SequenceEqual(state.DetectedSlimes))
        {
            SlimeEntries.RemoveAllChildren();
            foreach (var entry in state.DetectedSlimes)
            {
                Texture? icon = entry.Prototype is { } prototype
                    ? _systems.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(prototype.Id).Default
                    : null;
                SlimeEntries.AddChild(new XenobiologySpecimenEntryControl(entry, icon,
                    entry.Entity == state.SelectedSlime, () => SlimeSelected?.Invoke(entry.Entity)));
            }

            if (state.DetectedSlimes.Length == 0)
            {
                AddEmptyState(SlimeEntries, state.SelectedScanner == null
                    ? "xenobiology-console-select-scanner"
                    : "xenobiology-console-no-slimes");
            }
        }

        var prompt = state.SelectedScanner == null
            ? "xenobiology-console-select-scanner"
            : state.DetectedSlimes.Length == 0
                ? "xenobiology-console-no-slimes"
                : _state?.SelectedSlime != null && state.SelectedSlime == null &&
                  _state.SelectedScanner == state.SelectedScanner
                    ? "xenobiology-console-specimen-lost"
                    : "xenobiology-console-select-slime";
        EntityUid? specimen = null;
        if (state.SelectedSlime is { } selected && _entities.TryGetEntity(selected, out var local) &&
            local is { } uid && !_entities.Deleted(uid) && _entities.HasComponent<SpriteComponent>(uid))
            specimen = uid;

        ScanDetails.Populate(state.Scan, Loc.GetString(prompt), specimen);
        _state = state;
    }

    private void AddScannerEntry(string name, string fullName, bool selected, Action onSelected)
    {
        var button = new ContainerButton
        {
            ToolTip = fullName,
            HorizontalExpand = true,
            MinHeight = 32,
            ToggleMode = true,
            Pressed = selected
        };
        button.AddStyleClass(ContainerButton.StyleClassButton);
        button.AddChild(new XenobiologyNameLabel { FullText = name, ToolTip = fullName, Margin = new Thickness(4, 2) });
        button.OnPressed += _ =>
        {
            // Keep selection authoritative until the server accepts the request.
            button.Pressed = selected;
            onSelected();
        };
        ScannerEntries.AddChild(button);
    }

    private static void AddEmptyState(BoxContainer container, string key)
    {
        var label = new RichTextLabel { Margin = new Thickness(4, 8) };
        label.SetMessage(Loc.GetString(key));
        container.AddChild(label);
    }
}
