using Content.Client.UserInterface.Controls;
using Content.Shared._RedStar.Xenobiology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RedStar.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyConsoleWindow : FancyWindow
{
    public event Action<NetEntity>? ScannerSelected;
    public event Action<NetEntity>? SlimeSelected;

    private XenobiologyConsoleUiState? _state;

    public XenobiologyConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        AddEmptyState(ScannerEntries, "xenobiology-console-no-scanners");
        AddEmptyState(SlimeEntries, "xenobiology-console-select-scanner");
        ScanDetails.Populate(null, Loc.GetString("xenobiology-console-select-scanner"));
    }

    public void UpdateState(XenobiologyConsoleUiState state)
    {
        // Preserve scroll positions while only the analysis data changes.
        if (_state == null || _state.SelectedScanner != state.SelectedScanner ||
            !_state.LinkedScanners.SequenceEqual(state.LinkedScanners))
        {
            ScannerEntries.RemoveAllChildren();
            foreach (var entry in state.LinkedScanners)
            {
                AddEntry(ScannerEntries, entry.DisplayName, entry.Entity == state.SelectedScanner,
                    () => ScannerSelected?.Invoke(entry.Entity));
            }

            if (state.LinkedScanners.Length == 0)
                AddEmptyState(ScannerEntries, "xenobiology-console-no-scanners");
        }

        if (_state == null || _state.SelectedScanner != state.SelectedScanner ||
            _state.SelectedSlime != state.SelectedSlime ||
            !_state.DetectedSlimes.SequenceEqual(state.DetectedSlimes))
        {
            SlimeEntries.RemoveAllChildren();
            foreach (var entry in state.DetectedSlimes)
            {
                AddEntry(SlimeEntries, entry.DisplayName, entry.Entity == state.SelectedSlime,
                    () => SlimeSelected?.Invoke(entry.Entity));
            }

            if (state.DetectedSlimes.Length == 0)
            {
                AddEmptyState(SlimeEntries, state.SelectedScanner == null
                    ? "xenobiology-console-select-scanner"
                    : "xenobiology-console-no-slimes");
            }
        }

        var prompt = state.SelectedScanner == null
            ? "xenobiology-console-select-scanner"
            : state.DetectedSlimes.Length == 0
                ? "xenobiology-console-no-slimes"
                : _state?.SelectedSlime != null && state.SelectedSlime == null &&
                  _state.SelectedScanner == state.SelectedScanner
                    ? "xenobiology-console-specimen-lost"
                    : "xenobiology-console-select-slime";
        ScanDetails.Populate(state.Scan, Loc.GetString(prompt));
        _state = state;
    }

    private static void AddEntry(BoxContainer container, string name, bool selected, Action onSelected)
    {
        var button = new Button
        {
            Text = name,
            HorizontalExpand = true,
            MinHeight = 32,
            ToggleMode = true,
            Pressed = selected
        };
        button.OnPressed += _ =>
        {
            // Keep selection authoritative until the server accepts the request.
            button.Pressed = selected;
            onSelected();
        };
        container.AddChild(button);
    }

    private static void AddEmptyState(BoxContainer container, string key)
    {
        var label = new RichTextLabel { Margin = new Thickness(4, 8) };
        label.SetMessage(Loc.GetString(key));
        container.AddChild(label);
    }
}
