using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Admin.UI;

[GenerateTypedNameReferences]
public sealed partial class ModifyCharacterRecords : DefaultWindow
{
    public ModifyCharacterRecords()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var v in Enum.GetValues<CharacterRecordType>())
        {
            EntityEntryType.AddItem(v.ToString());
        }

        EntityEntryType.OnItemSelected += args =>
        {
            EntityEntryType.SelectId(args.Id);
            UpdateCommands();
        };

        EntityEdit.OnTextChanged += _ => UpdateCommands();
        EntityEntryIndex.OnTextChanged += _ => UpdateCommands();
        UpdateCommands();
    }

    private void UpdateCommands()
    {
        PurgeCommand.Command = null;
        DelCommand.Command = null;
        PurgeCommand.Disabled = true;
        DelCommand.Disabled = true;

        if (!int.TryParse(EntityEdit.Text, out var uid))
        {
            return;
        }

        PurgeCommand.Command = $"purgecharacterrecords {uid}";
        PurgeCommand.Disabled = false;
        if (!int.TryParse(EntityEntryIndex.Text, out var idx))
            return;

        var ty = (CharacterRecordType)EntityEntryType.SelectedId;
        DelCommand.Command = $"delrecordentry {uid} {ty.ToString()} {idx}";
        DelCommand.Disabled = false;
    }
}
