using Content.Shared._RedStar.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Text;
using System.Linq;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._RedStar.Botany;

[GenerateTypedNameReferences]
public sealed partial class RedStarPlantAnalyzerWindow : FancyWindow
{
    public Action<bool>? OnAdvancedModeChanged;

    private bool _advanced;

    public RedStarPlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        ModeButton.OnPressed += _ =>
        {
            _advanced = !_advanced;
            ModeButton.Text = Loc.GetString(_advanced
                ? "redstar-plant-analyzer-advanced-mode"
                : "redstar-plant-analyzer-basic-mode");
            OnAdvancedModeChanged?.Invoke(_advanced);
        };
    }

    public void Populate(RedStarPlantAnalyzerReport report)
    {
        _advanced = report.Advanced;
        ModeButton.Text = Loc.GetString(_advanced
            ? "redstar-plant-analyzer-advanced-mode"
            : "redstar-plant-analyzer-basic-mode");

        var output = new StringBuilder();
        output.AppendLine(Loc.GetString(report.IsPlant
            ? "redstar-plant-analyzer-scanned-plant"
            : "redstar-plant-analyzer-scanned-seed", ("name", Loc.GetString(report.SeedNameKey))));
        output.AppendLine();
        Add(output, "redstar-plant-analyzer-yield", report.Yield);
        Add(output, "redstar-plant-analyzer-potency", $"{report.Potency:0.#}%");
        Add(output, "redstar-plant-analyzer-harvest", Loc.GetString($"redstar-plant-analyzer-harvest-{report.HarvestType}"));
        Add(output, "redstar-plant-analyzer-endurance", $"{report.Endurance:0.#}");
        Add(output, "redstar-plant-analyzer-lifespan", $"{report.Lifespan:0.#}");
        Add(output, "redstar-plant-analyzer-maturation", $"{report.Maturation:0.#}");
        Add(output, "redstar-plant-analyzer-production", $"{report.Production:0.#}");
        Add(output, "redstar-plant-analyzer-growth-stages", report.GrowthStages);
        AddList(output, "redstar-plant-analyzer-chemistry", report.Chemicals, false);
        AddList(output, "redstar-plant-analyzer-consumes", report.ConsumedGases, false);
        AddList(output, "redstar-plant-analyzer-emits", report.EmittedGases, false);
        AddList(output, "redstar-plant-analyzer-mutations", report.PossibleMutations, false);

        if (report.Advanced)
        {
            output.AppendLine();
            output.AppendLine(Loc.GetString("redstar-plant-analyzer-advanced-heading"));
            Add(output, "redstar-plant-analyzer-genetic-instability", report.GeneticInstability.ToString("0.#"));
            Add(output, "redstar-plant-analyzer-nutrient-usage", report.NutrientConsumption.ToString("0.##"));
            Add(output, "redstar-plant-analyzer-water-usage", report.WaterConsumption.ToString("0.##"));
            Add(output, "redstar-plant-analyzer-ideal-heat", report.IdealHeat.ToString("0.#"));
            Add(output, "redstar-plant-analyzer-heat-tolerance", report.HeatTolerance.ToString("0.#"));
            Add(output, "redstar-plant-analyzer-toxins", report.ToxinsTolerance.ToString("0.#"));
            Add(output, "redstar-plant-analyzer-low-pressure", report.LowPressureTolerance.ToString("0.#"));
            Add(output, "redstar-plant-analyzer-high-pressure", report.HighPressureTolerance.ToString("0.#"));
            Add(output, "redstar-plant-analyzer-pests", report.PestTolerance.ToString("0.#"));
            Add(output, "redstar-plant-analyzer-weeds", report.WeedTolerance.ToString("0.#"));
            AddList(output, "redstar-plant-analyzer-traits", GetTraits(report));
        }

        Report.Text = output.ToString();
    }

    private static void Add(StringBuilder output, string key, object value)
    {
        output.AppendLine(Loc.GetString(key, ("value", value)));
    }

    private static void AddList(StringBuilder output, string key, IEnumerable<string> values, bool translateValues = true)
    {
        var localized = values.Select(value => translateValues ? Loc.GetString(value) : value).ToArray();
        output.AppendLine(Loc.GetString(key, ("value", localized.Length == 0 ? Loc.GetString("redstar-plant-analyzer-none") : string.Join(", ", localized))));
    }

    private static IEnumerable<string> GetTraits(RedStarPlantAnalyzerReport report)
    {
        if (report.Seedless)
            yield return "redstar-plant-analyzer-trait-seedless";
        if (report.Ligneous)
            yield return "redstar-plant-analyzer-trait-ligneous";
        if (report.CanScream)
            yield return "redstar-plant-analyzer-trait-screaming";
    }
}
